taskList = {
    "vmtoolsd.exe":"vmtool",
    "vmacthlp.exe":"vmtool",
    "VGAuthService.exe":"vmtool",
    "SynTPEnh.exe":"笔记本触摸板",
    "SynTPEnhService.exe":"笔记本触摸板",
    "vmware.exe":"VMware",
    "vmware-tray":"VMware",
    "WGestures.exe":"鼠标手势软件",
    "spoolsv.exe":"打印机驱动程序",
    "RadeonSoftware.exe":"AMD驱动软件",
    "QQProtect.exe":"QQ安全防护进程（Q盾）",
    "powershell.exe":"Windows PowerShell",
    "OneDrive.exe":"Microsoft OneDrive",
    "NutstoreWatchDog.exe":"坚果云",
    "NutstoreDriverSvc.exe":"坚果云",
    "Everything.exe":"Everything 搜索",
    "DingTalk.exe":"钉钉",
    "clash-win64.exe":"clash",
    "chrome.exe":"chrome",
    "Clash for Windows.exe":"Clash for Windows",
    "Code.exe":"Visual Studio Code",
    "firefox.exe":"Firefox",
    "Imagine.exe":"Imagine",
    "LogiOptions.exe":"LogiOptions",
    "vmnat.exe":"VMware NAT Service",
    "ida.exe":"ida",
    "ida64.exe":"ida64",
    "Xshell.exe":"Xshell",
    "XshellCore.exe":"Xshell",
    "NutstoreClient.exe":"坚果云",
    "WINWORD.EXE":"Microsoft Word",
    "java.exe":"java",
    "AnyDesk.exe":"AnyDesk",
    "SunloginClient.exe":"向日葵",
    "TeamViewer.exe":"TeamViewer",
    "TeamViewer_Service.exe":"TeamViewer",
    "tv_w32.exe":"TeamViewer",
    "tv_x64.exe":"TeamViewer",
    "navicat.exe":"navicat",
    "awrem32.exe":"pcanywhere",
    "Winaw32.exe":"pcanywhere",
    "r_server.exe":"radmin",
    "serv-u.exe":"server-u",
    "filezilla.exe":"filezilla client",
    "FileZilla Server.exe":"filezilla server",
    "Telegram.exe":"Telegram",
    "WeChatApp.exe":"微信",
    "WeChat.exe":"微信",
    "Wechat_Browser.exe":"微信",
    "wechatweb.exe":"微信",
    "OpenArk64.exe":"OpenArk",
    "geek.exe":"geek",
    "cloudmusic.exe":"网易云音乐",
    "ShadowsocksR-dotnet4.0.ex":"SSR",
    "dukto.exe":"dukto",
    "finalshell.exe": "finalshell终端管理",
    "mysqld.exe":"mysql",
    "php-cgi.exe":"php",
    "CloudHelper.exe":"安全狗/云视通",
    "G6FTPServer.exe":"Gene6 FTP Server",
    "G6FTPTray.exe":"Gene6 FTP",
    "Mini Mouse.exe":"Mini Mouse(有LFI和RCE)",
    "WechatBrowser.exe":"微信PC微信浏览器",
    "TNSLSNR.exe":"Oracle 数据库服务",
    "MsDtsSrvr.exe":"MicrosoftSQLServer",
    "vncserver.exe":"VNC",
    "Tomcat6.exe":"Tomcat6",
    "Tabby.exe":"Tabby 远程管理工具",
    "frps.exe":"frps",
    "frpc.exe":"frpc",
    "OpenVPNConnect.exe":"openvpn",
    "ovpnhelper_service.exe":"openvpn",
    "idea64.exe":"IDEA工具",
    "lghub_updater.exe":"罗技鼠标软件",
    "WeChatStore.exe":"微信",
    "Lsf.exe":"联想电脑管家",
};
